version: '3'
services:
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  nats:
    image: nats:2.10.9-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
      - "5050:5050"
    volumes:
      - ./nats.conf:/usr/src/app/nats.conf
    command: ["nats-server","-c","/usr/src/app/nats.conf"]
